# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2'],
    binaries=[],
    datas=[
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\sources\\logopng2.png', 'sources'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\sources\\Poppins-SemiBold.ttf', 'sources'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\sources\\empleados.png', 'sources'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\sources\\ordenes.png', 'sources'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\sources\\fundicion.png', 'sources'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\kivy_files\\pre_splash_screen.kv', 'kivy_files'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\kivy_files\\login_screen.kv', 'kivy_files'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\kivy_files\\home_screen.kv', 'kivy_files'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\kivy_files\\config_screen.kv', 'kivy_files'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\kivy_files\\empleados_screen.kv', 'kivy_files'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\kivy_files\\orders_screen.kv', 'kivy_files'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\kivy_files\\employee_details_screen.kv', 'kivy_files'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\kivy_files\\activity_selection_screen.kv', 'kivy_files'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\kivy_files\\fundido_screen.kv', 'kivy_files'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\kivy_files\\history_screen.kv', 'kivy_files'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\database\\db_manager.py', 'database'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\database\\config.ini', 'database'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\models\\employee_activity.py', 'models'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\models\\employee.py', 'models'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\models\\task.py', 'models'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\screens\\activity_selection_screen.py', 'screens'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\screens\\employee_details_screen.py', 'screens'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\screens\\orders_screen.py', 'screens'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\screens\\config_screen.py', 'screens'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\screens\\empleados_screen.py', 'screens'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\screens\\home_screen.py', 'screens'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\screens\\login_screen.py', 'screens'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\screens\\fundido_screen.py', 'screens'),
        ('C:\\Users\\lisan\\OneDrive\\Documentos\\Python proyects\\Fundicion\\App\\app_2\\screens\\history_screen.py', 'screens')
    ],
    hiddenimports=[
        'kivymd',
        'mysql.connector',
        'kivymd.uix.button',
        'kivymd.uix.label',
        'kivymd.uix.textfield',
        'kivymd.uix.datatables',
        'kivymd.uix.menu',
        'kivymd.uix.dialog',
        'kivymd.uix.relativelayout',
        'kivymd.uix.list',
        'kivymd.uix.responsivelayout',
        'kivymd.uix.floatlayout',
        'kivymd.uix.tab',
        'kivymd.toast',
        'kivymd.uix.dropdownitem',
        'kivymd.uix.selectioncontrol',
        'kivymd.uix.spinner',
        'kivymd.uix.behaviors',
        'kivymd.uix.navigationdrawer',
        'kivy.core.text',
        'kivy.graphics.stencil_instructions',
        'kivy.graphics.scissor_instructions',
        'kivy.graphics.vertex_instructions',
        'kivy.graphics.context_instructions',
        'kivy.graphics.fbo',
        'kivy.graphics.instructions',
        'kivy.graphics.texture',
        'kivy.graphics.vbo',
        'kivy.lib.gstplayer',
        'PIL._imaging',
        'PIL._imagingtk',
        'kivymd.uix.screenmanager',
        'PIL._imagingft',
        'PIL._imagingcms',
        'PIL._webp',
        'configparser',
        'datetime',
        'os',
        'threading',
        're',
        'mysql.connector.pooling',
        'kivymd.uix.screen',
        'kivymd.uix.menu',
        'kivy.properties',
        'kivymd.app',
        'kivy.clock',
        'kivy.lang',
        'functools',
        'kivy.metrics',
        'kivymd.uix.boxlayout',
        'kivymd.uix.card',
        'kivy.uix.scrollview',
        'kivy.uix.screenmanager',
        'kivy.resources'
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=True,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='main',
)
